remote:
  mongo:
    url: aliyun
    port: 30017
    username: root
    password: 123
    database: bill-sys

billClass:
  食品: [食堂三餐, 外卖, 奶茶, 外出吃饭, 饮料, 零食, 水果]
  交通: [公交, 打车, 火车, 自行车, 飞机]
  购物: [日用品, 衣服裤子, 化妆饰品, 美容护肤, 鞋帽包包, 运动装备, 淘宝剁手]
  寝室: [洗衣服, 电费, 洗澡沐浴, 热水]
  娱乐: [聚会吃饭, 电影, 社团费用]
  学习: [书籍, 文具, 培训进修, 考试报名]
  恋爱: [一起吃饭, 一起电影, 一起旅游, 约会, 开房, 红包, 礼物]
  人情: [送礼, 请客, 慈善捐助, 礼金红包]
  医疗: [药品, 治疗, 门诊]
  通讯: [话费, 网费]
  网络: [会员]
  数码: []
  其他: []
